### ISSUE TITLE
Unable to use aracne.jar executable

### ISSUE THREAD

**Issue by gspirito** [califano-lab/ARACNe-AP#5]
Hello, I've build the jar with `ant main` as indicated with no errors (openjdk version "1.8.0_212"), but if I run `java -jar ./aracne.jar` I get this error: 

Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at aracne.Aracne.main(Unknown Source)

What is the cause of that?

Thank you in advance.

**Comment by grosenberger** [comment]
Hi, this is actually the expected behavior. Unfortunately, the current version of ARACNe doesn't have a help menu by default. You can invoke it by ``java -jar ./aracne.jar -h``.

**Comment by gspirito** [comment]
Thank you!

**Comment by biginfor** [comment]
Hello, I wonder if you have solved this problem? It also bothered me for a long time. I would appreciate for any help！

**Comment by biginfor** [comment]
The error is caused by the source file format.

**Comment by sudheshnabodapati** [comment]
> java -jar ./aracne.jar

@biginfor @grosenberger 
Do you what the issue is exactly because when I type in   java -jar ./aracne.jar it gives me the same error and tells me nothing new 
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at aracne.Aracne.main(Unknown Source)
Can someone explain me what does this mean?

**Comment by grosenberger** [comment]
You need to supply the argument `-h`, please see above answer.

**Comment by sudheshnabodapati** [comment]
It says invalid argument when I do that

**Comment by sudheshnabodapati** [comment]
> java -jar ./aracne.jar -h
@grosenberger 
Unknown option '-h'
Is what Im getting when Im trying to do that

**Comment by MrDotOne** [comment]
I have the same issue

[root@cc-dclrilog61 dist]# java -jar ./aracne.jar
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at aracne.Aracne.main(Unknown Source)

[root@cc-dclrilog61 dist]# java -jar ./aracne.jar -h
Unknown option '-h'

Any ideas?
